### ISSUE TITLE
Melhorar validação do gateway

### ISSUE THREAD

**Issue by luizbills** [DevelopersRede/rede-woocommerce#22]
Atualmente os campos como cartão de crédito e número de parcelas estão sendo validados no método `process_payment`. O correto é usar o método `validate_fields`. O método `process_payment` deve ser exclusivo para "processar o pagamento", pois naquele momento o pedido já foi criado.

No método `validate_fields`, se houver erros, eles podem ser enviados ao front pelo método `\wc_add_notice( $error_message, 'error' );`

**Comment by marcos-alexandre82** [comment]
Mais informações em:

https://docs.woocommerce.com/document/payment-gateway-api/
