### ISSUE TITLE
Exibindo bandeira de cartão incorreta no checkout

### ISSUE THREAD

**Issue by davilotus** [DevelopersRede/rede-woocommerce#26]
Ao informar um número de cartão de crédito Elo é exibida a bandeira da Mastercard

**Comment by marcos-alexandre82** [comment]
@davilotus , vc baixou a última versão que subi no meu respositório que corrigia as bandeiras? Se sim, os dois primeiros dígitos do cartão Elo é 65 ou 60?

**Comment by davilotus** [comment]
Eu atualizei, mas deu um erro fatal no arquivo **class-wc-rede-api.php na linha 20**.
Fiz um teste local com uma instalação limpa do WordPress com o tema Twentynine e o erro foi o mesmo.
