### ISSUE TITLE
Anti-fraude

### ISSUE THREAD

**Issue by AlyCav** [DevelopersRede/rede-woocommerce#27]
Olá, esse plugin já tem o anti-fraude da rede?

**Comment by icaroferreir0** [comment]
Estou com a mesma dúvida, você conseguiu respostas ?

**Comment by marcos-alexandre82** [comment]
Sim, o antifraude já está integrado ao plugin, porém é sempre bom utilizar mais de um método de verificação em sua loja, para diminuir ainda mais os riscos de fraudes.

**Comment by willjosefi** [comment]
olá @marcos-alexandre82 
onde especificamente está sendo configurado o antifraude neste plugin?
revirei o código-fonte e não encontrei nada que utilizasse o antifraude deles

**Comment by marcos-alexandre82** [comment]
@willjosefi, chegou a baixar a última [release](https://github.com/DevelopersRede/woocommerce/releases) completa?
Está dentro da pasta vendor:
https://prnt.sc/ri51ch

Em todo caso, eu enviei um fork com alguns ajustes/implementações para o repositório oficial de plugins:
https://wordpress.org/plugins/woo-rede/

:)

**Comment by netojoaobatista** [comment]
O antifraude foi removido dessa versão e não está mais disponível - nem no módulo, nem no SDK. O recurso está passando por revisão de regra de negócio.

**Comment by rickdroio** [comment]
olá, @netojoaobatista alguma atualização sobre o antifraude? obrigado
