### ISSUE TITLE
Não permite ingressar os dados do cartão

### ISSUE THREAD

**Issue by hammerkaos** [DevelopersRede/rede-woocommerce#28]
Olá pessoal. Estou com problemas com o módulo do e-Rede no Woocommerce. 

Atualmente, uso a versão 3.8.1 do Woocommerce, versão 5.3 do Wordpress e a versão 1.0.0 do e-Rede (uso essa versão porque as versão atualizada ocasiona um erro fatal na página, deixando tudo em branco).

No checkout, quando clico na opção para pagamento com e-Rede, não permite ingrassar os dados do cartão, nem outro dado disponível no formulário; só me permite selecionar a quantidade de parcelas.

No log do sistema, aparece o erro:

```
> 2019-12-03T22:26:06+00:00 CRITICAL Uncaught Error: Call to undefined method WP_Post::get_id() in /home/festaeconfeito/public_html/wp-content/plugins/rede-woocommerce/rede-woocommerce.php:174
> Stack trace:
> #0 /home/festaeconfeito/public_html/wp-includes/class-wp-hook.php(288): update_rede_orders()
> #1 /home/festaeconfeito/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
> #2 /home/festaeconfeito/public_html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
> #3 /home/festaeconfeito/public_html/wp-cron.php(138): do_action_ref_array('update_rede_ord...', Array)
> #4 {main}
>   thrown, em /home/festaeconfeito/public_html/wp-content/plugins/rede-woocommerce/rede-woocommerce.php, na linha 174
```

Alguém me poderia ajudar com isso, por favor?

**Comment by marcos-alexandre82** [comment]
Olá @hammerkaos ,

Estou com um pull request aguardando ser aceito. Até lá, você já testou utilizar a versão que está no meu repositório?

https://github.com/marcos-alexandre82/woocommerce/tree/develop

Se ainda não testou, consegue testar e dar o feedback aqui?

**Comment by hammerkaos** [comment]
Olá @marcos-alexandre82 ,

Testei com essa versão que você comentou e também acontece o mesmo problema; ao ativar o plugin, tudo fica em branco e a página mostra um erro. Tenho que desativar o plugin pra voltar ao normal. Somente com a versão 1.0.0 é que isso não acontece e posso alterar as configurações normalmente do e-Rede, porém não permite ingressar os dados do cartão no checkout.

**Comment by marcos-alexandre82** [comment]
@hammerkaos , você colocou a pasta vendor (pode fazer o download aqui: https://github.com/DevelopersRede/woocommerce/releases/tag/1.2.1) dentro do diretório rede-woocommerce que baixou do meu repositório?

Chegou a excluir (fazendo backup antes) o plugin antigo (versão 1.0.0)?

Testei aqui em um novo ambiente com o tema WordPress 5.3 + Storefront 2.5.3 + WooCommerce 3.8.1 + Brazilian Market on WooCommerce  3.7.2 e funcionou corretamente.

Já tentou desativar, em um ambiente de homologação, os demais plugins deixando apenas estes e com um tema padrão para ver se o erro não é causado pelo tema ou outro plugin?

Uma opção também é utilizar o plugin https://br.wordpress.org/plugins/health-check/ para que um eventual teste no site em produção não seja refletido para o usuário final.

Não esquece de dar o feedback ;)

**Comment by hammerkaos** [comment]
@marcos-alexandre82 , desculpa a demora pra responder. Coloquei a pasta vendor dentro do diretório rede-woocommerce e parou o erro, porém não mostravam as informações digitadas nos campos do cartão. Inspecionei o código e vi que era um conflito com o template, que tinha no css um valor de font-size: 1.5em; e por isso não mostrava nada pelo tamanho da letra. Tenso! Hahaha 

Mas consegui resolver. Agora vou fazer algumas compras com os cartões de teste e ver se valida tudo ok. Comunicarei qualquer novidade.

**Comment by hammerkaos** [comment]
@marcos-alexandre82 tentei enviar essas informações no outro chat, mas não permite por alguma razão.

Essa é a tela das configurações, com os dados do PV e Token omitidos:

https://prnt.sc/qag4gb

E esse é o relatório gerado pelo sistema: https://pastebin.com/KrLSMhPs

**Comment by divulgaabc** [comment]
> @marcos-alexandre82 , desculpa a demora pra responder. Coloquei a pasta vendor dentro do diretório rede-woocommerce e parou o erro, porém não mostravam as informações digitadas nos campos do cartão. Inspecionei o código e vi que era um conflito com o template, que tinha no css um valor de font-size: 1.5em; e por isso não mostrava nada pelo tamanho da letra. Tenso! Hahaha
> 
> Mas consegui resolver. Agora vou fazer algumas compras com os cartões de teste e ver se valida tudo ok. Comunicarei qualquer novidade.

Qual foi a solução quer você encontrou? Estou tendo o mesmo problema, não aparece o campo para digitar os dados do cartão, é somente selecionável as parcelas.

**Comment by divulgaabc** [comment]
@hammerkaos, qual foi a solução quer você encontrou? Estou tendo o mesmo problema, não aparece o campo para digitar os dados do cartão, é somente selecionável as parcelas.

**Comment by hammerkaos** [comment]
@divulgaabc no meu caso, alterei o código css a continuação:

`
input[type="text"], input[type="password"], input[type="email"], input[type="number"], input[type="tel"], input[type="date"], input[type="search"], textarea, select, .select2-container .select2-selection--single .select2-selection__rendered {
    font-size: 15px !important;
}
`

Depois disso, não era possível validar os cartões no ambiente de produção. O que tive que fazer foi solicitar à Rede que me habilitem o site em modo produção e a solução deles foi gerar um novo PV porque supostamente o que eu tinha era para teste.

Tenta essas soluções que provavelmente irão funcionar. Comigo deu certo pelo menos :)

**Comment by icaroferreir0** [comment]
A opção de Anti Fraude está funcionada para vocês ?

**Comment by netojoaobatista** [comment]
Esse erro já foi corrigido na última release.
