### ISSUE TITLE
Erro: "Softdescriptor: Not enabled for this merchant."

### ISSUE THREAD

**Issue by SouzaTeles** [DevelopersRede/rede-woocommerce#30]
Olá, estou tentando fazer a primeira compra de testes no meu site woocommerce (ambiente em produção), no entanto ao finalizar é apresentado o seguinte erro no log: 

> "Softdescriptor: Not enabled for this merchant.""

Alguém me poderia ajudar com isso, por favor?

**Comment by netojoaobatista** [comment]
Segundo a [documentação](https://www.userede.com.br/desenvolvedores/pt/produto/e-Rede#documentacao-softdescriptor):

> Para utilizar essa funcionalidade, acesse o portal da Rede no menu e.Rede > Identificação na fatura ou entre em contato com a Central de atendimento da Rede. Caso o nome não seja cadastrado, o serviço não será habilitado.
>
> Após a habilitação do serviço via portal, a funcionalidade será disponibilizada dentro de um prazo de até 24 horas.

Chegou a seguir o procedimento?

**Comment by wwwcardoso** [comment]
https://github.com/DevelopersRede/rede-woocommerce/issues/1#issuecomment-478247665
