### ISSUE TITLE
[1.2.2][BUG] Falha ao atualizar pedidos

### ISSUE THREAD

**Issue by jsvini** [DevelopersRede/rede-woocommerce#31]
O método que atualiza o status dos pedidos `update_rede_orders` faz a chama de um método que não existe: `$order->get_id()`, essa variável é do tipo `WP_Post`  e a mesma não possui o método `get_id()`.

https://github.com/DevelopersRede/woocommerce/blob/0a948cb28a7f8ceabc4a121f3f5cbff19aee55d7/rede-woocommerce/rede-woocommerce.php#L175

Log do erro do Wordpress:

Um erro do tipo E_ERROR foi causado na linha 175 do arquivo /home/[...]/plugins/rede-woocommerce/rede-woocommerce.php. 
Mensagem de erro: Uncaught Error: Call to undefined method WP_Post::get_id()

**Comment by luizbill** [comment]
Mesmo erro por aqui. Aparentemente começou com a atualização do Wordpress 5.4

**Comment by marcos-alexandre82** [comment]
@jsvini e @luizbill , vocês já testaram a versão que está no repositório de plugins do WordPress?

**Comment by jsvini** [comment]
@marcos-alexandre82 se for esse plugin https://br.wordpress.org/plugins/woo-rede/ possui o mesmo bug:

https://plugins.trac.wordpress.org/browser/woo-rede/trunk/integration-rede-for-woocommerce.php#L191

**Comment by marcos-alexandre82** [comment]
@jsvini get_id é um método herdado do WC_Data:
https://docs.woocommerce.com/wc-apidocs/class-WC_Order.html
Fiz um teste ontem, em um ambiente com Storefront, WordPress e WooCommerce em suas últimas versões, não recebi o erro e o status foi alterado normalmente. Também estou utilizando em site em produção sem erros.

Consegue detalhar melhor para eu tentar replicar?

**Comment by jsvini** [comment]
@marcos-alexandre82 o `WP_Query` retorna objetos `WP_Post`, no contexto abaixo `$orders->posts` é uma lista de objetos `WP_Post`, que não possuem o método `get_id()`.

No `foreach` a variável `$order` é um `WP_Post` e não um `WC_Order`

https://github.com/DevelopersRede/woocommerce/blob/0a948cb28a7f8ceabc4a121f3f5cbff19aee55d7/rede-woocommerce/rede-woocommerce.php#L166-L178

**Comment by marcos-alexandre82** [comment]
Olá,

Imagino que está mensagem tenha sido enviada por e-mail quando a versão do WordPress foi atualizada, certo?

Qual versão do PHP, do plugin WooCommerce, tema (qual e versão, caso não tenha sido desenvolvido por você) e WordPress está utilizando?

Este aviso deve ter sido enviado quando a versão do WordPress do seu site foi atualizada, mas o plugin do WooCommerce ainda estava em uma versão antiga.

Tentei reproduzir o erro em um ambiente de testes com o WordPress 5.4.1, tema Storefront 2.5.5, plugin WooCommerce 4.0.1 e com meu plugin na versão 2.0.0 e não recebi o erro, além disso, as alterações no status do pedido ocorrem normalmente.

Consegue me passar as informações acima e me dizer se está tendo problemas com as alterações de status dos pedidos?
