### ISSUE TITLE
mensagem de erro no pagamento.

### ISSUE THREAD

**Issue by fabianamanu** [DevelopersRede/rede-woocommerce#34]
ola  estou com o seguinte erro de acordo coma imagem a baixo

![image](https://user-images.githubusercontent.com/12700210/94930330-9ff56180-049c-11eb-89dd-f18ead4fac8d.png)

**Comment by qrcomunicacao** [comment]
Estou com mesmo problema.

Notice: Undefined property: WC_Rede_Debit::$auto_capture in /home/ideiaria/public_html/wp-content/plugins/rede-woocommerce/includes/class-wc-rede-api.php on line 36

Notice: Undefined property: WC_Rede_Debit::$partner_gateway in /home/ideiaria/public_html/wp-content/plugins/rede-woocommerce/includes/class-wc-rede-api.php on line 38

Notice: Undefined property: WC_Rede_Debit::$partner_module in /home/ideiaria/public_html/wp-content/plugins/rede-woocommerce/includes/class-wc-rede-api.php on line 39

**Comment by fabianamanu** [comment]
oie  tudo bem ? eu entrei em contato com a rede e meu erro foi resolvido ,  pois eles possuem uma versão antiga do site ao  tive que  mudar o nome    la dentro do site deles  me foi enviado esta seguinte operação 


O cliente está no site novo, é essencial ele acessar o site antigo. 

No canto superior direito matriz ao clicar em tem a opção ir para o site antigo. 

Já no site antigo, clicar em > Meu Usuário (no canto superior direito) e clicar em > Acessar outra filial

Para castrar o softdescriptor basta seguir ps seguintes passos: 

Logar com o e-mail e senha já cadastrados no Portal da Rede: www.userede.com.br, 

1° No canto superior direito Matriz clicar em  > Ir para o site antigo;

2º Já no site antigo, clicar em > Meu Usuário (no canto superior direito) e clicar em > Acessar outra filial

3º Na filial do e-commerce aparecerá o menu e.Rede na tarja laranja, clicar em > Menu e.Rede > Identificação na fatura.

 

A identificação na fatura é composta por duas partes: 

- A primeira, de 8 caracteres, é fixa por PV e deve ser cadastrada abaixo. 

- A segunda parte, de até 13 caracteres, é dinâmica e enviada na mensageria de integração, por transação.

 

Após a habilitação do serviço via portal, a funcionalidade será disponibilizada dentro de um prazo de até 24 horas
