### ISSUE TITLE
Warning include_once autoload

### ISSUE THREAD

**Issue by fernandoplanejar91** [DevelopersRede/rede-woocommerce#35]
Fiz o upload dos arquivos mas está apresentando a seguinte mensagem de erro:

Warning: include_once(/plugins/rede-woocommerce-master/vendor/autoload.php): failed to open stream: No such file or directory in /plugins/rede-woocommerce-master/rede-woocommerce.php on line 99

Notei que esse arquivo ( vendor/autoload.php ) não consta no diretório da pasta.

**Comment by marcos-alexandre82** [comment]
@fernandoplanejar91 chegou a baixar a última release, conforme mencionado no primeiro parágrafo da descrição?

Se não, esse é o link:

https://github.com/DevelopersRede/woocommerce/releases/latest/download/rede-woocommerce.zip

**Comment by fernandoplanejar91** [comment]
Consegui resolver o problema acima usando esse outro plugin:

https://github.com/DevelopersRede/rede-woocommerce/releases/tag/2.0.1

Mas agora aparece outro erro:

------------------

[04-Nov-2020 13:26:34 UTC] PHP Notice:  Undefined property: WC_Rede_Debit::$auto_capture in /wp-content/plugins/rede-woocommerce/includes/class-wc-rede-api.php on line 36

[04-Nov-2020 13:26:34 UTC] PHP Notice:  Undefined property: WC_Rede_Debit::$partner_gateway in /wp-content/plugins/rede-woocommerce/includes/class-wc-rede-api.php on line 38

[04-Nov-2020 13:26:34 UTC] PHP Notice:  Undefined property: WC_Rede_Debit::$partner_module in /wp-content/plugins/rede-woocommerce/includes/class-wc-rede-api.php on line 39

------------------

Mesmo desativando a opção de cartão de débito o erro permanece.

Além disso aparece outra mensagem de erro:

------------------

Cartão de Crédito: erro no pagamento.

------------------

**Comment by netojoaobatista** [comment]
> Mas agora aparece outro erro:

Esses avisos foram removidos na nova release.

> Cartão de Crédito: erro no pagamento.

Crie um diretório de log e ative o log de depuração do módulo:

![Captura de tela de 2020-11-09 19-20-06](https://user-images.githubusercontent.com/273586/98603358-adceab80-22c0-11eb-8279-15c1f14a1191.png)

Depois que ativar o log, você vai conseguir ver exatamente o motivo da transação não ter sido aprovada.
