### ISSUE TITLE
Compatibilidade com a versão 4.6.0 do WooCommerce

### ISSUE THREAD

**Issue by joaovictorpsantos** [DevelopersRede/rede-woocommerce#36]
Fala pessoal, tudo bem?

Primeiramente queria agradecer por todo o trabalho de criar o plugin da E.Rede para o WooCommerce e disponibilizar as Issues para as dúvidas, show de bola!!

Atualmente eu estou usando em um projeto as seguintes versões:

WordPress 5.4.2
WooCommerce 4.6.0

E estou começando a integração com o plugin https://br.wordpress.org/plugins/woo-rede/ pois o plugin oficial ainda não possui suporte para essa versão do WooCommerce.

Vocês teriam uma data ou planejamento de quando vocês pretendem lançar a versão compatível com o 4.6.0 do WooCommerce?

**Comment by marcos-alexandre82** [comment]
@joaovictorpsantos você chegou a testar em um ambiente de homologação a última release aqui desse repositório? Creio que, por mais que não mencione no readme, deva funcionar sim com a versão 4.6.0 do WooCommerce, pois eu tbm não atualizei ainda a flag no meu plugin, embora ele esteja funcionando na 4.6.0 ;)

**Comment by joaovictorpsantos** [comment]
@marcos-alexandre82 eu tentei a utilização da ultima release do plugin aqui do repositório, ele instalava normalmente mas quando eu ia configurar ele aparecia um aviso de que a versão plugin não era compatível com a versão do WordPress, então resolvi utilizar o seu fork!! hehehe no momento estou configurando ele, esperando as chaves de acesso do ambiente de teste do cliente.

**Comment by marcos-alexandre82** [comment]
@joaovictorpsantos , ele dava um aviso na página de instalação? Este aviso era de que não havia sido testado com a versão do WooCommerce que você utiliza mas não impedia a instalação, certo?

Seria legal, se conseguir testar em um ambiente de homologação e, se funcionar tudo certinho, abrir uma issue aqui ou enviar um pull request com a alteração da versão testada no arquivo rede-woocommerce.php, incluindo os seguintes parâmetros (abaixo do parâmetro  '* Requires at least: 5.5' - linha 10), substituindo os números das versões pelas versões que testar:

* Tested up to: 5.5.3
* WC requires at least: 3.0.0
* WC tested up to: 4.6.2

 ;)

**Comment by netojoaobatista** [comment]
O módulo acabou de ser testado com a 4.6.2 e está tudo certo. Existem algumas outras atualizações que também foram feitas e estão na última release.
